num_procs:
  pfls: 15
  pfcp: 15
  pfcm: 15
  pfls_thread: 50
  pfcp_thread: 50
  pfcm_thread: 50

pftool:
  fuse_dir: "/archive/fusemnt"

active_nodes:
  gpfst1: "ON"
  gpfst2: "ON"
  gpfst3: "ON"
  gpfst4: "ON"
  gpfst5: "ON"
  gpfst6: "ON"
  gpfst7: "ON"
  gpfst8: "ON"
  gpfst9: "ON"
  gpfst10: "ON"
