num_procs:
  pfls: 15
  pfcp: 24

pftool:
  fuse_dir: "/archive/fusemnt"

active_nodes:
  gpfst1: "ON"
  gpfst2: "ON"
  gpfst3: "ON"
  gpfst4: "ON"
  gpfst5: "ON"
  gpfst6: "ON"
  gpfst7: "ON"
  gpfst8: "ON"
  gpfst9: "ON"
  gpfst10: "ON"
