num_procs:
  pfls: 15
  pfcp: 25
  pfcm: 15

pftool:
  fuse_dir: "/archive/fusemnt"

active_nodes:
  gpfst1: "OFF"
  gpfst2: "OFF"
  gpfst3: "OFF"
  gpfst4: "OFF"
  gpfst5: "OFF"
  gpfst6: "OFF"
  gpfst7: "OFF"
  gpfst8: "OFF"
  gpfst9: "OFF"
  gpfst10: "ON"
